/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "var(--color-surface-container)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-tint": "var(--color-surface-tint)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-background": "var(--color-on-background)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary-fixed": "var(--color-primary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        secondary: "var(--color-secondary)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        outline: "var(--color-outline)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        background: "var(--color-background)",
        "on-surface": "var(--color-on-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        surface: "var(--color-surface)",
        "surface-bright": "var(--color-surface-bright)",
        primary: "var(--color-primary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary": "var(--color-on-secondary)",
        "brand-green": "var(--color-brand-green)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        base: "8px",
        "container-margin": "20px",
        gutter: "16px",
      },
      fontSize: {
        /* Sesuai desain sistem: Maksimal font-weight 600 (Semibold), tidak boleh 700 */
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "numeric-data": ["24px", { lineHeight: "24px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};